controller_list:
  - name: fake_jaka_zu7_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: jaka_zu7
    pose: zero