controller_list:
  - name: fake_jaka_s5_controller
    # type: $(arg fake_execution_type)
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: jaka_s5
    pose: zero